### PR TITLE
git-show show HEAD if no commit specified

### PR DESCRIPTION
**Pull request by fmnoise**

### CODE REVIEW

**Comment by akonwi** [comment]
If you enter `head` it achieves the same thing. I wouldn't want to have a null input result in valid output. Because there is an input required I think there should be a responsibility to enter which commit to show.

There are two alternatives I'm more comfortable with:
 1. Change the placeholder of the input to make it clear that the default will be HEAD
 2. Create a second command with the label 'Show HEAD' that won't show the input as a second step

Could you also add tests around what you add?

**Comment by fmnoise** [comment]
Actually now it just fails silently if nothing has entered(if you'll open dev tools console there's an error)
image

That's why I decided to make command execution most close as it is when you enter `git show` in console without adding any commit hash.
I'll add some tests.
Also not sure why do we need this code, as it's does nothing
https://github.com/akonwi/git-plus/blob/master/lib/models/git-show.coffee#L53

**Comment by akonwi** [comment]
Yea understandable. Will you go the route of making it obvious in the placeholder that it will default to HEAD?

Feel free to remove line 53 as well

**Comment by akonwi** [comment]
I've merged this

**Pull request closed without merging**
