### PR TITLE
Add edit config file commands

### PR DESCRIPTION
**Pull request by danielbayley**
- Add edit excludes command
- Add edit global config command

### CODE REVIEW

**Comment by danielbayley** [comment]
I just need to figure out the correct spec for [spec/models/git-edit-global-config-spec.coffee](https://github.com/akonwi/git-plus/pull/487/commits/3788e4e2be38ff21722986a0caeacb9681f5f7d9#diff-99168b2ee64ddacda0801c49a77ae47b) and get it passing.

@akonwi Any ideas on that?

**Comment by akonwi** [comment]
I've been busy but I'm excited to see your PRs. I'll review them tonight.

Thanks!

**Comment by akonwi** [comment]
I need to do more investigation here. 

There's a function called `cmd` in `lib/git.coffee` which executes git commands in a child process and provides a Promise interface. That's what most of the commands in the package delegate to. You may want to use that instead of requiring child_process. [Here is an example](https://github.com/akonwi/git-plus/blob/master/lib/models/git-branch.coffee#L33#L38)

**Comment by akonwi** [comment]
I just pushed some changes on top of this into a branch called 487 in my repo. I changed the test for the excludes command because it wasn't actually running and included the Path module to join filepaths

**Pull request closed without merging**
