### PR TITLE
Implement auto-fetch

### LINKED ISSUE #632: [REQUEST]: Auto-fetch
How about an auto-`fetch` feature like some of the GUI git clients out there? (Tower and GitKraken both do this)… `--all` could be an option, as well as being able to specify an `interval:`.

### PR DESCRIPTION
**Pull request by danielbayley**
Closes #632.

### CODE REVIEW

**Comment by akonwi** [comment]
This is cool. Is the icon appearing in the notification for you? It isn't showing for me. I thought it was because of the theme I'm using but I've switched to a few including the default atom themes and I don't see anything. I've also removed the icon option and it should default to a check mark but I don't see that either

**Comment by akonwi** [comment]
I set this as an experimental feature to start. Maybe after a month or two if things look good we can make it a core setting

**Comment by danielbayley** [comment]
Cool. It's been running on my local copy without a hitch since I pushed this PR so should be no problems…

**Comment by akonwi** [comment]
Yea it seems solid. I'm weary of people coming out of the woodwork with issues around it. 

The experimental label is intended to show the feature is beta and there is potentially a higher likelihood of Issues. In the three years I've maintained this package, I've learned that everyone uses git differently and as people use different combinations of packages and development environments, really odd problems will arise

**Pull request merged**
